name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Check for outdated dependencies
        run: npm outdated
      
      # Uncomment to use Dependabot or similar tools
      # - name: Create Pull Request for dependency updates
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: Update dependencies
      #     title: 'chore: update dependencies'
      #     body: |
      #       Automated dependency updates
      #     branch: dependency-updates